# core/chapters_data.py

SYLLABUS = {
    'sslc': {
        'physics': [
            {'id': 1, 'name': 'Effects of Electric Current', 'file_url': '/media/sslc/phy/phy_ch1.pdf'},
            {'id': 2, 'name': 'Magnetic Effects of Electric Current',
                'file_url': '/media/sslc/phy/ch2.pdf'},
            {'id': 3, 'name': 'Electromagnetic Induction',
                'file_url': '/media/sslc/phy/ch3.pdf'},
            {'id': 4, 'name': 'Reflection of Light',
                'file_url': '/media/sslc/phy/ch4.pdf'},
            {'id': 5, 'name': 'Refraction of Light',
                'file_url': '/media/sslc/phy/ch5.pdf'},
            {'id': 6, 'name': 'Vision and the World of Colour',
                'file_url': '/media/sslc/phy/ch6.pdf'},
            {'id': 7, 'name': 'Energy Management',
                'file_url': '/media/sslc/phy/ch7.pdf'},
        ],
        'chemistry': [
            {'id': 1, 'name': 'Periodic Table and Electronic Configuration',
                'file_url': '/media/sslc/chem/ch1.pdf'},
            {'id': 2, 'name': 'Gas Laws and Mole Concept',
                'file_url': '/media/sslc/chem/ch2.pdf'},
            {'id': 3, 'name': 'Reactivity Series and Electrochemistry',
                'file_url': '/media/sslc/chem/ch3.pdf'},
            {'id': 4, 'name': 'Production of Metals',
                'file_url': '/media/sslc/chem/ch4.pdf'},
            {'id': 5, 'name': 'Compounds of Non-Metals',
                'file_url': '/media/sslc/chem/ch5.pdf'},
            {'id': 6, 'name': 'Nomenclature of Organic Compounds',
                'file_url': '/media/sslc/chem/ch6.pdf'},
            {'id': 7, 'name': 'Chemical Reactions of Organic Compounds',
                'file_url': '/media/sslc/chem/ch7.pdf'},
        ],
        'biology': [
            {'id': 1, 'name': 'Sensations and Responses',
                'file_url': '/media/sslc/bio/ch1.pdf'},
            {'id': 2, 'name': 'Windows of Knowledge',
                'file_url': '/media/sslc/bio/ch2.pdf'},
            {'id': 3, 'name': 'Chemical Messages for Homeostasis',
                'file_url': '/media/sslc/bio/ch3.pdf'},
            {'id': 4, 'name': 'Keeping Diseases Away',
                'file_url': '/media/sslc/bio/ch4.pdf'},
            {'id': 5, 'name': 'Soldiers of Defense',
                'file_url': '/media/sslc/bio/ch5.pdf'},
            {'id': 6, 'name': 'Unravelling Genetic Mysteries',
                'file_url': '/media/sslc/bio/ch6.pdf'},
            {'id': 7, 'name': 'Genetics for the Future',
                'file_url': '/media/sslc/bio/ch7.pdf'},
            {'id': 8, 'name': 'The Paths We Traverse',
                'file_url': '/media/sslc/bio/ch8.pdf'},
        ],
        'mathematics': [
            {'id': 1, 'name': 'Arithmetic Sequences',
                'file_url': '/media/sslc/math/ch1.pdf'},
            {'id': 2, 'name': 'Circles', 'file_url': '/media/sslc/math/ch2.pdf'},
            {'id': 3, 'name': 'Mathematics of Chance',
                'file_url': '/media/sslc/math/ch3.pdf'},
            {'id': 4, 'name': 'Second Degree Equations',
                'file_url': '/media/sslc/math/ch4.pdf'},
            {'id': 5, 'name': 'Trigonometry',
                'file_url': '/media/sslc/math/ch5.pdf'},
            {'id': 6, 'name': 'Coordinates', 'file_url': '/media/sslc/math/ch6.pdf'},
            {'id': 7, 'name': 'Tangents', 'file_url': '/media/sslc/math/ch7.pdf'},
            {'id': 8, 'name': 'Solids', 'file_url': '/media/sslc/math/ch8.pdf'},
            {'id': 9, 'name': 'Geometry and Algebra',
                'file_url': '/media/sslc/math/ch9.pdf'},
            {'id': 10, 'name': 'Polynomials',
                'file_url': '/media/sslc/math/ch10.pdf'},
            {'id': 11, 'name': 'Statistics', 'file_url': '/media/sslc/math/ch11.pdf'},
        ],
        'english': [
            {'id': 1, 'name': 'Adventures in a Banyan Tree',
                'file_url': '/media/sslc/english/ch1.pdf'},
            {'id': 2, 'name': 'The Snake and the Mirror', 'file_url': '/media/sslc/english/ch2.pdf'},
            {'id': 3, 'name': 'Lines Written in Early Spring ',
                'file_url': '/media/sslc/english/ch3.pdf'},
            {'id': 4, 'name': 'Project Tiger',
                'file_url': '/media/sslc/english/ch4.pdf'},
            {'id': 5, 'name': 'Blowin in the Wind',
                'file_url': '/media/sslc/english/ch5.pdf'},
            {'id': 6, 'name': 'Vanka', 'file_url': '/media/sslc/english/ch6.pdf'},
            {'id': 7, 'name': 'The Ballad of Father Gilligan', 'file_url': '/media/sslc/english/ch7.pdf'},
            {'id': 8, 'name': 'The Best Investment I Ever Made', 'file_url': '/media/sslc/english/ch8.pdf'},
            {'id': 9, 'name': 'The Danger of a Single Story',
                'file_url': '/media/sslc/english/ch9.pdf'},
            {'id': 10, 'name': 'The Scholarship Jacket',
                'file_url': '/media/sslc/english/ch10.pdf'},
            {'id': 11, 'name': 'Poetry', 'file_url': '/media/sslc/english/ch11.pdf'},
        ],
        'geography': [
            {'id': 1, 'name': 'Seasons and Time',
                'file_url': '/media/sslc/geography/ch1.pdf'},
            {'id': 2, 'name': 'In Search of the Source of Wind', 'file_url': '/media/sslc/geography/ch2.pdf'},
            {'id': 3, 'name': 'High Skies and Answers ',
                'file_url': '/media/sslc/geography/ch3.pdf'},
            {'id': 4, 'name': 'Blanket of Earth',
                'file_url': '/media/sslc/geography/ch4.pdf'},
            {'id': 5, 'name': 'Terrain Analysis through Maps',
                'file_url': '/media/sslc/geography/ch5.pdf'},
            {'id': 6, 'name': 'Eyes in the Sky and Data Analysis', 'file_url': '/media/sslc/geography/ch6.pdf'},
            {'id': 7, 'name': 'India: The Land of Diversities', 'file_url': '/media/sslc/geography/ch7.pdf'},
            {'id': 8, 'name': 'Resource Wealth of India', 'file_url': '/media/sslc/geography/ch8.pdf'},
            {'id': 9, 'name': 'Financial Literacy',
                'file_url': '/media/sslc/geography/ch9.pdf'},
            {'id': 10, 'name': 'Consumer: State and Situation',
                'file_url': '/media/sslc/geography/ch10.pdf'},
        ],
        'history': [
            {'id': 1, 'name': 'Revolutions that Influenced the World',
                'file_url': '/media/sslc/history/ch1.pdf'},
            {'id': 2, 'name': 'World in the Twentieth Century', 'file_url': '/media/sslc/history/ch2.pdf'},
            {'id': 3, 'name': 'Public Administration ',
                'file_url': '/media/sslc/history/ch3.pdf'},
            {'id': 4, 'name': 'British Exploitation and Resistance',
                'file_url': '/media/sslc/history/ch4.pdf'},
            {'id': 5, 'name': 'Culture and Nationalism',
                'file_url': '/media/sslc/history/ch5.pdf'},
            {'id': 6, 'name': 'Struggle and Freedom', 'file_url': '/media/sslc/history/ch6.pdf'},
            {'id': 7, 'name': 'India after Independence', 'file_url': '/media/sslc/histoey/ch7.pdf'},
            {'id': 8, 'name': 'Kerala towards Modernity', 'file_url': '/media/sslc/history/ch8.pdf'},
            {'id': 9, 'name': 'The State and Political Science',
                'file_url': '/media/sslc/history/ch9.pdf'},
            {'id': 10, 'name': 'Civic Consciousness',
                'file_url': '/media/sslc/history/ch10.pdf'},
            {'id': 11, 'name': 'Sociology: What? Why?',
                'file_url': '/media/sslc/history/ch10.pdf'},
        ],
        
        
    },
    'plus-one': {
        'physics': [
            {'id': 1, 'name': 'Units and Measurements',
                'file_url': '/media/p1/phy/ch1.pdf'},
            {'id': 2, 'name': 'Motion in a Straight Line',
                'file_url': '/media/p1/phy/ch2.pdf'},
            {'id': 3, 'name': 'Motion in a Plane',
                'file_url': '/media/p1/phy/ch3.pdf'},
            {'id': 4, 'name': 'Laws of Motion',
                'file_url': '/media/p1/phy/ch4.pdf'},
            {'id': 5, 'name': 'Work, Energy and Power',
                'file_url': '/media/p1/phy/ch5.pdf'},
            {'id': 6, 'name': 'System of Particles and Rotational Motion',
                'file_url': '/media/p1/phy/ch6.pdf'},
            {'id': 7, 'name': 'Gravitation', 'file_url': '/media/p1/phy/ch7.pdf'},
        ],
        'mathematics': [
            {'id': 1, 'name': 'Sets', 'file_url': '/media/p1/math/ch1.pdf'},
            {'id': 2, 'name': 'Relations and Functions',
                'file_url': '/media/p1/math/ch2.pdf'},
            {'id': 3, 'name': 'Trigonometric Functions',
                'file_url': '/media/p1/math/ch3.pdf'},
            {'id': 4, 'name': 'Complex Numbers',
                'file_url': '/media/p1/math/ch4.pdf'},
            {'id': 5, 'name': 'Linear Inequalities',
                'file_url': '/media/p1/math/ch5.pdf'},
        ],
        'chemistry': [
            {'id': 1, 'name': 'Some Basic Concepts of Chemistry',
                'file_url': '/media/p1/chem/ch1.pdf'},
            {'id': 2, 'name': 'Structure of Atom',
                'file_url': '/media/p1/chem/ch2.pdf'},
           {'id': 3, 'name': 'Classification of Elements and Periodicity in Properties',
                'file_url': '/media/p1/chem/ch3.pdf'},
            {'id': 4, 'name': 'Chemical Bonding and Molecular Structure',
                'file_url': '/media/p1/chem/ch4.pdf'},
            {'id': 5, 'name': 'Thermodynamics',
                'file_url': '/media/p1/chem/ch5.pdf'},
            {'id': 6, 'name': 'Equilibrium',
                'file_url': '/media/p1/chem/ch6.pdf'},
            {'id': 7, 'name': 'Redox Reactions', 'file_url': '/media/p1/chem/ch7.pdf'},
            {'id': 8, 'name': 'Hydrogen',
                'file_url': '/media/p1/chem/ch8.pdf'},
            {'id': 9, 'name': 'The s-Block Elements',
                'file_url': '/media/p1/chem/ch9.pdf'},
            {'id': 10, 'name': 'The p-Block Elements',
                'file_url': '/media/p1/chem/ch10.pdf'},
            {'id': 11, 'name': 'Organic Chemistry: Some Basic Principles and Techniques',
                'file_url': '/media/p1/chem/ch11.pdf'},
            {'id': 12, 'name': 'Hydrocarbons',
                'file_url': '/media/p1/chem/ch12.pdf'},
            {'id': 13, 'name': 'Environmental Chemistry',
                'file_url': '/media/p1/chem/ch13.pdf'},
        ],
         'botany': [
            {'id': 1, 'name': 'Biological Classification',
                'file_url': '/media/p1/bot/ch1.pdf'},
            {'id': 2, 'name': 'Plant Kingdom',
                'file_url': '/media/p1/bot/ch2.pdf'},
           {'id': 3, 'name': 'Morphology of Flowering Plants',
                'file_url': '/media/p1/bot/ch3.pdf'},
            {'id': 4, 'name': 'Anatomy of Flowering Plants',
                'file_url': '/media/p1/bot/ch4.pdf'},
            {'id': 5, 'name': 'Cell: The Unit of Life',
                'file_url': '/media/p1/bot/ch5.pdf'},
            {'id': 6, 'name': 'Cell Cycle and Cell Division',
                'file_url': '/media/p1/bot/ch6.pdf'},
            {'id': 7, 'name': 'Transport in Plants', 'file_url': '/media/p1/bot/ch7.pdf'},
            {'id': 8, 'name': 'Mineral Nutrition',
                'file_url': '/media/p1/bot/ch8.pdf'},
            {'id': 9, 'name': 'Photosynthesis in Higher Plants',
                'file_url': '/media/p1/bot/ch9.pdf'},
            {'id': 10, 'name': 'Respiration in Plants',
                'file_url': '/media/p1/bot/ch10.pdf'},
            {'id': 11, 'name': 'Plant Growth and Development',
                'file_url': '/media/p1/bot/ch11.pdf'},
        ],
         'zoology': [
            {'id': 1, 'name': 'The Living World"',
                'file_url': '/media/p1/zoo/ch1.pdf'},
            {'id': 2, 'name': 'Animal Kingdom',
                'file_url': '/media/p1/zoo/ch2.pdf'},
           {'id': 3, 'name': 'Structural Organisation in Animals',
                'file_url': '/media/p1/zoo/ch3.pdf'},
            {'id': 4, 'name': 'Biomolecules',
                'file_url': '/media/p1/zoo/ch4.pdf'},
            {'id': 5, 'name': 'Digestion and Absorption',
                'file_url': '/media/p1/zoo/ch5.pdf'},
            {'id': 6, 'name': 'Breathing and Exchange of Gases',
                'file_url': '/media/p1/zoo/ch6.pdf'},
            {'id': 7, 'name': 'Body Fluids and Circulation', 'file_url': '/media/p1/zoo/ch7.pdf'},
            {'id': 8, 'name': 'Excretory Products and their Elimination',
                'file_url': '/media/p1/zoo/ch8.pdf'},
            {'id': 9, 'name': 'Locomotion and Movement',
                'file_url': '/media/p1/zoo/ch9.pdf'},
            {'id': 10, 'name': 'Neural Control and Coordination',
                'file_url': '/media/p1/zoo/ch10.pdf'},
            {'id': 11, 'name': 'Chemical Coordination and Integration',
                'file_url': '/media/p1/zoo/ch11.pdf'},
        ]
    },
    'plus-two': {
        'physics': [
            {'id': 1, 'name': 'Electric Charges and Fields',
                'file_url': '/media/p2/phy/ch1.pdf'},
            {'id': 2, 'name': 'Electrostatic Potential and Capacitance',
                'file_url': '/media/p2/phy/ch2.pdf'},
            {'id': 3, 'name': 'Current Electricity',
                'file_url': '/media/p2/phy/ch3.pdf'},
            {'id': 4, 'name': 'Moving Charges and Magnetism',
                'file_url': '/media/p2/phy/ch4.pdf'},
            {'id': 5, 'name': 'Magnetism and Matter',
                'file_url': '/media/p2/phy/ch5.pdf'},
            {'id': 6, 'name': 'Electromagnetic Induction',
                'file_url': '/media/p2/phy/ch6.pdf'},
            {'id': 7, 'name': 'Alternating Current',
                'file_url': '/media/p2/phy/ch7.pdf'},
            {'id': 8, 'name': 'Electromagnetic Waves',
                'file_url': '/media/p2/phy/ch8.pdf'},
            {'id': 9, 'name': 'Ray Optics and Optical Instruments',
                'file_url': '/media/p2/phy/ch9.pdf'},
            {'id': 10, 'name': 'Wave Optics', 'file_url': '/media/p2/phy/ch10.pdf'},
        ],
        'chemistry': [
            {'id': 1, 'name': 'Solutions', 'file_url': '/media/p2/chem/ch1.pdf'},
            {'id': 2, 'name': 'Electrochemistry',
                'file_url': '/media/p2/chem/ch2.pdf'},
            {'id': 3, 'name': 'Chemical Kinetics',
                'file_url': '/media/p2/chem/ch3.pdf'},
            {'id': 4, 'name': 'The d- and f- Block Elements',
                'file_url': '/media/p2/chem/ch4.pdf'},
            {'id': 5, 'name': 'Coordination Compounds',
                'file_url': '/media/p2/chem/ch5.pdf'},
            {'id': 6, 'name': 'Haloalkanes and Haloarenes',
                'file_url': '/media/p2/chem/ch6.pdf'},
        ],
        'accountancy': [
            {'id': 1, 'name': 'Accounting for Partnership: Basic Concepts',
                'file_url': '/media/p2/acc/ch1.pdf'},
            {'id': 2, 'name': 'Reconstitution of a Partnership Firm – Admission of a Partner',
                'file_url': '/media/p2/acc/ch2.pdf'},
            {'id': 3, 'name': 'Reconstitution of a Partnership Firm – Retirement/Death of a Partner',
                'file_url': '/media/p2/acc/ch3.pdf'},
            {'id': 4, 'name': 'Dissolution of Partnership Firm',
                'file_url': '/media/p2/acc/ch4.pdf'},
            {'id': 5, 'name': 'Accounting for Share Capital',
                'file_url': '/media/p2/acc/ch5.pdf'},
            {'id': 6, 'name': 'Issue and Redemption of Debentures',
                'file_url': '/media/p2/acc/ch6.pdf'},
        ],
        'computer-science': [
            {'id': 1, 'name': 'Structures and Pointers',
                'file_url': '/media/p2/cs/ch1.pdf'},
            {'id': 2, 'name': 'Concepts of Object Oriented Programming',
                'file_url': '/media/p2/cs/ch2.pdf'},
            {'id': 3, 'name': 'Data Structures and Algorithms',
                'file_url': '/media/p2/cs/ch3.pdf'},
            {'id': 4, 'name': 'Web Technology', 'file_url': '/media/p2/cs/ch4.pdf'},
            {'id': 5, 'name': 'Database Management System',
                'file_url': '/media/p2/cs/ch5.pdf'},
        ],
        'mathematics': [
            {'id': 1, 'name': 'Relations and Functions',
                'file_url': '/media/p2/math/ch1.pdf'},
            {'id': 2, 'name': 'Inverse Trigonometric Functions',
                'file_url': '/media/p2/math/ch2.pdf'},
            {'id': 3, 'name': 'Matrices', 'file_url': '/media/p2/math/ch3.pdf'},
            {'id': 4, 'name': 'Determinants', 'file_url': '/media/p2/math/ch4.pdf'},
            {'id': 5, 'name': 'Continuity and Differentiability',
                'file_url': '/media/p2/math/ch5.pdf'},
            {'id': 6, 'name': 'Application of Derivatives',
                'file_url': '/media/p2/math/ch6.pdf'},
            {'id': 7, 'name': 'Integrals', 'file_url': '/media/p2/math/ch7.pdf'},
            {'id': 8, 'name': 'Application of Integrals',
                'file_url': '/media/p2/math/ch8.pdf'},
            {'id': 9, 'name': 'Differential Equations',
                'file_url': '/media/p2/math/ch9.pdf'},
            {'id': 10, 'name': 'Vector Algebra',
                'file_url': '/media/p2/math/ch10.pdf'},
            {'id': 11, 'name': 'Three Dimensional Geometry',
                'file_url': '/media/p2/math/ch11.pdf'},
            {'id': 12, 'name': 'Linear Programming',
                'file_url': '/media/p2/math/ch12.pdf'},
            {'id': 13, 'name': 'Probability', 'file_url': '/media/p2/math/ch13.pdf'},
        ]
    }
}
